(include_subdirs no)

(library
  (name utils)
  (package mlang)
  (flags (:standard -open Utils_common -open Platform))
  (modules strSet setExt pp mapExt strMap setSetExt intSet
           errors intMap sorting
           charMap strings topologicalSorting utils)
  (libraries dune-build-info platform utils_common))

(library
  (name utils_common)
  (package mlang)
  (modules pos dgfip_m config))

(library
  (name platform)
  (package mlang)
  (flags(:standard -open Utils_common))
  (modules cli file dgfip_options)
  (libraries utils_common dune-build-info)
  (virtual_modules cli file dgfip_options))
