(include_subdirs no)

(library
  (name utils)
  (package mlang)
  (modules strSet setExt pp mapExt strMap setSetExt intSet
           errors intMap config dgfip_m sorting
           charMap strings topologicalSorting)
  (libraries cmdliner ANSITerminal dune-build-info threads platform))

(library
  (name utils_common)
  (package mlang)
  (modules pos))

(library
  (name platform)
  (package mlang)
  (flags(:standard -open Utils_common))
  (modules cli file dgfip_options)
  (libraries utils_common)
  (virtual_modules cli file))
