(include_subdirs unqualified)

(library
 (public_name mlang)
 (flags
  (:standard -open Utils -open M_ir))
 (preprocess (pps ppx_deriving_yojson))
 (libraries
  re
  ANSITerminal
  parmap
  dune-build-info
  num
  menhirLib
  ocamlgraph
  m_ir
  utils))

(documentation
 (package mlang)
 (mld_files ("index")))
